### ISSUE TITLE
how to add custom plugins for custom requirement

### ISSUE THREAD

**Issue by ghost** [walkmod/walkmod-sonar-plugin#16]
Hi
   It is really a good automation tool, which i love to use it for our bigger project. we have our custom rules for which i need auto fix. But standard plugins does not provide me the solution. so i would like to provide my custom effort to fix those violations.

below are few rules we have 
1 .Replace all tab characters in this file by sequences of white-spaces
2.Public types, methods and fields (API) should be documented with Javadoc

please let me know how to provide custom plugin for my purpose. any samples will be really helpfull

**Comment by rpau** [comment]
Thanks, this is awesome. 

First of all, let me ask one question: how do you detect that a file contains tabs instead of whitespaces? Could you point me out the rule and the engine (e,g Sonarqube, rule: xxx)

I think that the second one is a rule from SonarQube. If this is the case, you simply need to create a PR in this repo, which is full of examples. The problem I see about documentation, is that it could be helpful for getters/setter, but it is not possible for other methods.

Here you have slides to explain how to add more SonarQuebe rules: https://es.slideshare.net/RaquelPau/sonar-rules-in-action-with-walkmod

**Comment by ghost** [comment]
first rule is part of sonar rule, and there is way to handle this in eclipse IDE, and i have tested it. 

also below link for your reference
http://www.gomadeeasy.com/2017/03/sonar-replace-all-tab-characters-in.html

for second rule.

i mainly focus on the methods other than setters and getters, can you please point out the difficulty in implementing for methods, other than set and get methods?, and scope of customization?

**Comment by rpau** [comment]
@prabaharanit about the first rule:
Walkmod already supports eclipse formatter. You need to create/modify your walkmod.xml to use the formatter. Do you have any walkmod.xml file? If not, please could you tell me which command do you use?

About the second rule, you need to take in mind that AFAIK, there is not any algorithm to generate human readable text from code. This is the reason why IDEs (e.g eclipse) cannot do this. It is not a walkmod limitation, it is a non-resolved problem, and more importantly, it cannot be shared in this plugin because it will affect to all the users providing a code transformation that is not deterministic, and thus, unexpected.

**Comment by ghost** [comment]
@rpau,  below is my walkmod.xml

	<chain name="main-chain">
        <reader path="src/main/java"/>
        <walker>
            <transformations>
            	<transformation type="imports-cleaner"/>
            </transformations>
        </walker>
        <writer path="src/main/java">
            <param name="configFile">eclipse-formatter.xml</param>
        </writer>
    </chain>

and can you direct me, how to use eclipse formatter in walkmod, i belief , the eclipse formatter will apply during writing phase, i mean after applying imports cleaner transformation. pls correct me if i am wrong.
Also share me if you have sample formatter.xml, i have searched over, but in vain. and documentation on this also helps me to move further.

on second rule. i understand this is very specific issue, and i would like to provide my implementation for our project by forking.  but as you said before, if walkmod applies on setters and getters, that will solve 1/4 of my issue.. pls advice..

**Comment by rpau** [comment]
@prabaharanit Everything is right, BUT walkmod only will re-write the files that have been modified by any transformation (the `imports-cleaner` in your case). If you want to rewrite everything (no matters if there are imports to remove or not), you need to add the `onlyWriteChanges` param as follows:

```
<chain name="main-chain">
        <reader path="src/main/java"/>
        <walker>
            <param name="onlyWriteChanges">false</param>
            <transformations>
            	<transformation type="imports-cleaner"/>
            </transformations>
        </walker>
        <writer path="src/main/java">
            <param name="configFile">eclipse-formatter.xml</param>
        </writer>
    </chain>
```

The default applied Eclipse formatter configuration is this one:
 [https://github.com/rpau/walkmod-cfg/blob/master/src/main/resources/formatter.xml](https://github.com/rpau/walkmod-cfg/blob/master/src/main/resources/formatter.xml). The documentation of every single property appears in the [Eclipse javadoc site](http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fformatter%2FDefaultCodeFormatterConstants.html).

By default is formatting using spaces (check `org.eclipse.jdt.core.formatter.tabulation.char`) in the XML file and `org.eclipse.jdt.core.formatter.indentation.size`, which means that 1 tab = 3 spaces.

This file is stored in your $WALKMOD_HOME/conf directory, where WALKMOD_HOME is where you have installed walkmod from the command line. If I were you, I would copy this file in the repository, then I would modify what I need, and check if it works. You do not need a plugin if you do not need to use this same eclipse formatter settings in different repositories (for avoiding copy-paste).

If you have any issue and you want to contribute, the repository to fork is this one:
https://github.com/walkmod/walkmod-java-formatter-plugin

**Comment by rpau** [comment]
@prabaharanit I am assuming this issue has been fixed. Feel free to reopen it if there is anything else to address.
